name: Terraform
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
      - name: Terraform Init
        run: ./tf.sh prod init
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: ./tf.sh prod plan -out=tfplan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: ./tf.sh prod apply -auto-approve tfplan
